version: "3.9"

services:
  app:
    image: ghcr.io/madhuryadutta/docker-swarm:latest
    networks:
      - prod_net
    environment:
      SERVICE_NAME: "{{.Service.Name}}"
      TASK_NAME: "{{.Task.Name}}"
      TASK_ID: "{{.Task.ID}}"
      NODE_ID: "{{.Node.ID}}"
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - target: 80
        published: 80
        protocol: tcp

networks:
  prod_net:
    external: true
